spring:
    datasource:
        url: "jdbc:mariadb://localhost:3306/sid"
        username: "digi-suivi"
        password: "pazo1928!"
        driver-class-name: org.mariadb.jdbc.Driver
    servlet:
        multipart:
            max-file-size: "10MB"
            max-request-size: "10MB"
    jpa:
        database: mysql
        generate-ddl: false
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    thymeleaf: # Thymeleaf
        cache: true
        mode: HTML
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0
jwt:
    cookie: "AUTH-TOKEN"
    expires_in: 864000
    secret: "3dDsYHtBkTz0gAoPmPMwL2ksjVfVyR2Js0OsaVTx3RobUGI6YGM3gWJRFhPG"
logging:
    level:
      org.springframework: WARN
      org.hibernate.type.descriptor: trace
      org.hibernate.sql: debug
server:
    http2:
        enabled: true
    port: 8080
    ssl:
        key-store: classpath:keystore.jks
        key-store-password: pazo1928!
