spring:
    profiles:
        active: prod
    datasource:
        url: '@jdbc.url@'
        username: '@jdbc.user@'
        password: '@jdbc.pass@'
        driver-class-name: '@jdbc.driver@'
    servlet:
        multipart:
            max-file-size: "10MB"
            max-request-size: "10MB"
    jpa:
        database: mysql
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    thymeleaf: # Thymeleaf
        cache: true
        mode: HTML
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 3600
jwt:
    cookie: "AUTH-TOKEN"
    expires_in: 864000
    secret: "3dOnmPOBkTz0gtoPmJMwB5kejVfVsRsJs8OsaVsxsRsNUGI6YGM6gWJRFhKG"
logging:
    level:
      org.springframework: WARN
      org.hibernate.type.descriptor: warn
      org.hibernate.sql: error
server:
    http2:
        enabled: true
prod:
    url: '@prod.url@'
    photo : '@prod.photo@'
---
spring:
    profiles:
        active: dev
    datasource:
        url: '@jdbc.url@'
        username: '@jdbc.user@'
        password: '@jdbc.pass@'
        driver-class-name: '@jdbc.driver@'
        tomcat:
            max-active: '@jdbc.connections.max.active@'
            max-idle: '@jdbc.connections.max.active@'
    jpa:
        database: mysql
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    servlet:
        multipart:
            max-file-size: "10MB"
            max-request-size: "10MB"
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
    web:
        resources:
            static-locations: file:src/main/resources/static/
            cache:
                period: 0
jwt:
    cookie: "AUTH-TOKEN"
    expires_in: 864000
    secret: "3dOnmPOBkTz0gtoPmJMwB5kejVfVsRsJs8OsaVsxsRsNUGI6YGM6gWJRFhKG"
logging:
    level:
        org.springframework: WARN
        org.hibernate.type.descriptor: debug
        org.hibernate.sql: trace
server:
    port: 8090
    http2:
        enabled: true
