create table ADMINISTRATION_SESSION (
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    ID_SESSION BIGINT(20),
    ID_UTILISATEUR BIGINT(20),
    STATUS_RESPONSABLE_SESSION TINYINT(1),
    FOREIGN KEY (ID_SESSION) REFERENCES SESSION(ID),
    FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID)
);